# ShareMap Configuration Schema with Validation Enhancements
# Always sent by the gateway
# Always received by the USX
config:
  # ============================================
  # PSK CC TX Configuration
  # ============================================
  psk_cc_tx_force_on:
    type: boolean
    desc: Force the channel to always be on.
    path: radio/psk_cc/tx/config/force_on
    default: false
    
  psk_cc_tx_idle_timeout_s:
    type: u64
    desc: Power down channel after being idle for specified time.
    path: radio/psk_cc/tx/config/idle_timeout_s
    default: 10
    min: 0
    max: 3600
    unit: seconds
    
  psk_cc_tx_fe_frequency:
    type: f64
    desc: Frequency to transmit at.
    path: radio/psk_cc/tx/config/fe/frequency
    default: 2.24e9
    min: 1.0e6
    max: 10.0e9
    unit: Hz
    
  psk_cc_tx_fe_stx1_enable:
    type: boolean
    desc: Enable STX1 channel (STX2 must be disabled).
    path: radio/psk_cc/tx/config/fe/rf_channels/STX1/enable
    default: true
    mutex_with: psk_cc_tx_fe_stx2_enable
    
  psk_cc_tx_fe_stx1_gain:
    type: f64
    desc: Gain setting for STX1.
    path: radio/psk_cc/tx/config/fe/rf_channels/STX1/gain
    default: 60
    min: 0
    max: 89.75
    step: 0.25
    unit: dB
    
  psk_cc_tx_fe_stx1_atten:
    type: f64
    desc: Digital step attenuator setting for STX1.
    path: radio/psk_cc/tx/config/fe/rf_channels/STX1/atten
    default: 15
    min: 0
    max: 31.75
    step: 0.25
    unit: dB
    
  psk_cc_tx_fe_stx2_enable:
    type: boolean
    desc: Enable STX2 channel (STX1 must be disabled).
    path: radio/psk_cc/tx/config/fe/rf_channels/STX2/enable
    default: false
    mutex_with: psk_cc_tx_fe_stx1_enable
    
  psk_cc_tx_fe_stx2_gain:
    type: f64
    desc: Gain setting for STX2.
    path: radio/psk_cc/tx/config/fe/rf_channels/STX2/gain
    default: 60
    min: 0
    max: 89.75
    step: 0.25
    unit: dB
    
  psk_cc_tx_fe_stx2_atten:
    type: f64
    desc: Digital step attenuator setting for STX2.
    path: radio/psk_cc/tx/config/fe/rf_channels/STX2/atten
    default: 15
    min: 0
    max: 31.75
    step: 0.25
    unit: dB
    
  psk_cc_tx_fe_sample_rate:
    type: f64
    desc: Sample rate of the ad9361. The sample rate for all channels using the ad9361 should match if they are in active use (i.e. psk_cc tx/rx and dvbs2).
    path: radio/psk_cc/tx/config/fe/sample_rate
    default: 20.48e6
    min: 521e3
    max: 61.44e6
    unit: Hz
    
  psk_cc_tx_symbol_rate:
    type: f64
    desc: Symbol rate of the waveform.
    path: radio/psk_cc/tx/config/symbol_rate
    default: 650e3
    min: 1e3
    max: 30.72e6
    unit: symbols/s
    
  psk_cc_tx_modulation:
    type: string
    desc: "Symbol modulation config: BPSK/QPSK"
    path: radio/psk_cc/tx/config/modulation
    default: QPSK
    options:
      - BPSK
      - QPSK

  # ============================================
  # PSK CC RX Configuration
  # ============================================
  psk_cc_rx_force_on:
    type: boolean
    desc: Force the channel to always be on.
    path: radio/psk_cc/rx/config/force_on
    default: true
    
  psk_cc_rx_idle_timeout_s:
    type: u64
    desc: Power down channel after being idle for specified time.
    path: radio/psk_cc/rx/config/idle_timeout_s
    default: 10
    min: 0
    max: 3600
    unit: seconds
    
  psk_cc_rx_low_power_timeout_s:
    type: u64
    desc: Power up channel after being in powered down for specified time.
    path: radio/psk_cc/rx/config/low_power_timeout_s
    default: 1
    min: 0
    max: 3600
    unit: seconds
    
  psk_cc_rx_gain_mode:
    type: string
    desc: "Gain mode. Valid values are: MANUAL, SLOW_AGC, FAST_AGC, and HYBRID_AGC."
    path: radio/psk_cc/rx/config/gain_mode
    default: SLOW_AGC
    options:
      - MANUAL
      - SLOW_AGC
      - FAST_AGC
      - HYBRID_AGC
      
  psk_cc_rx_auto_antenna_selection:
    type: boolean
    desc: "Enable automatic antenna selection."
    path: radio/psk_cc/rx/config/auto_antenna_selection
    default: false
    
  psk_cc_rx_fe_frequency:
    type: f64
    desc: Frequency to receive from.
    path: radio/psk_cc/rx/config/fe/frequency
    default: 2.065e9
    min: 1.0e6
    max: 10.0e9
    unit: Hz
    
  psk_cc_rx_fe_srx1_enable:
    type: boolean
    desc: Enable SRX1 channel (SRX2 must be disabled).
    path: radio/psk_cc/rx/config/fe/rf_channels/SRX1/enable
    default: true
    mutex_with: psk_cc_rx_fe_srx2_enable
    
  psk_cc_rx_fe_srx1_gain:
    type: f64
    desc: Gain setting for SRX1.
    path: radio/psk_cc/rx/config/fe/rf_channels/SRX1/gain
    default: 45
    min: 0
    max: 76
    step: 1
    unit: dB
    
  psk_cc_rx_fe_srx1_atten:
    type: f64
    desc: Digitial step attenuator setting for SRX1.
    path: radio/psk_cc/rx/config/fe/rf_channels/SRX1/atten
    default: 15
    min: 0
    max: 31.75
    step: 0.25
    unit: dB
    
  psk_cc_rx_fe_srx2_enable:
    type: boolean
    desc: Enable SRX2 channel (SRX1 must be disabled).
    path: radio/psk_cc/rx/config/fe/rf_channels/SRX2/enable
    default: false
    mutex_with: psk_cc_rx_fe_srx1_enable
    
  psk_cc_rx_fe_srx2_gain:
    type: f64
    desc: Gain setting for SRX2.
    path: radio/psk_cc/rx/config/fe/rf_channels/SRX2/gain
    default: 45
    min: 0
    max: 76
    step: 1
    unit: dB
    
  psk_cc_rx_fe_srx2_atten:
    type: f64
    desc: Digital step attenuator setting for SRX2.
    path: radio/psk_cc/rx/config/fe/rf_channels/SRX2/atten
    default: 15
    min: 0
    max: 31.75
    step: 0.25
    unit: dB
    
  psk_cc_rx_fe_sample_rate:
    type: f64
    desc: Sample rate of the ad9361. The sample rate for all channels using the ad9361 should match if they are in active use (i.e. psk_cc tx/rx and dvbs2).
    path: radio/psk_cc/rx/config/fe/sample_rate
    default: 20.48e6
    min: 521e3
    max: 61.44e6
    unit: Hz
    
  psk_cc_rx_symbol_rate:
    type: f64
    desc: Symbol rate of the waveform.
    path: radio/psk_cc/rx/config/symbol_rate
    default: 320e3
    min: 1e3
    max: 30.72e6
    unit: symbols/s
    
  psk_cc_rx_modulation:
    type: string
    desc: "Symbol modulation config: BPSK/QPSK"
    path: radio/psk_cc/rx/config/modulation
    default: QPSK
    options:
      - BPSK
      - QPSK

  # ============================================
  # DVB-S2 TX Configuration
  # ============================================
  dvbs2_tx_force_on:
    type: boolean
    desc: Force the channel to always be on.
    path: radio/dvbs2/tx/config/force_on
    default: false
    
  dvbs2_tx_idle_timeout_s:
    type: u64
    desc: Power down channel after being idle for specified time.
    path: radio/dvbs2/tx/config/idle_timeout_s
    default: 10
    min: 0
    max: 3600
    unit: seconds
    
  dvbs2_tx_fe_frequency:
    type: f64
    desc: Frequency to transmit at.
    path: radio/dvbs2/tx/config/fe/frequency
    default: 8.488e9
    min: 1.0e6
    max: 12.0e9
    unit: Hz
    
  dvbs2_tx_fe_gain:
    type: f64
    desc: Gain setting for dvbs2 TX.
    path: radio/dvbs2/tx/config/fe/gain
    default: 69
    min: 0
    max: 89.75
    step: 0.25
    unit: dB
    
  dvbs2_tx_fe_sample_rate:
    type: f64
    desc: Sample rate of the ad9361. The sample rate for all channels using the ad9361 should match if they are in active use (i.e. psk_cc tx/rx and dvbs2).
    path: radio/dvbs2/tx/config/fe/sample_rate
    default: 16e6
    min: 521e3
    max: 61.44e6
    unit: Hz
    
  dvbs2_tx_symbol_rate:
    type: f64
    desc: Symbol rate.  Must be integer division of sample rate.
    path: radio/dvbs2/tx/config/symbol_rate
    default: 4e6
    min: 1e3
    max: 30.72e6
    unit: symbols/s
    
  dvbs2_tx_modulation:
    type: string
    desc: "Modulation to use. Valid values are: unmodulated, QPSK, 8PSK, 16APSK, and 32APSK."
    path: radio/dvbs2/tx/config/modulation
    default: QPSK
    options:
      - unmodulated
      - QPSK
      - 8PSK
      - 16APSK
      - 32APSK
      
  dvbs2_tx_coding:
    type: string
    desc: "Error correction code to use. Valid values are: 1/4, 1/3, 2/5, 1/2, 3/5, 2/3, 3/4, 4/5, 5/6, 8/9, 9/10, 11/45, 4/15, 14/45, 7/15, 8/15, 26/45, and 32/45."
    path: radio/dvbs2/tx/config/coding
    default: "1/4"
    options:
      - "1/4"
      - "1/3"
      - "2/5"
      - "1/2"
      - "3/5"
      - "2/3"
      - "3/4"
      - "4/5"
      - "5/6"
      - "8/9"
      - "9/10"
      - "11/45"
      - "4/15"
      - "14/45"
      - "7/15"
      - "8/15"
      - "26/45"
      - "32/45"
      
  dvbs2_tx_rolloff:
    type: string
    desc: "Filter rolloff. Valid values are: 35%, 25%, 20%, 15%, 10%, 5%, and the empty string for no rolloff."
    path: radio/dvbs2/tx/config/rolloff
    default: "35%"
    options:
      - "35%"
      - "25%"
      - "20%"
      - "15%"
      - "10%"
      - "5%"
      - ""
      
  dvbs2_tx_frame_length:
    type: string
    desc: "Frame length type to use. Valid values are: SHORT, NORMAL, and LONG."
    path: radio/dvbs2/tx/config/frame_length
    default: NORMAL
    options:
      - SHORT
      - NORMAL
      - LONG
      
  dvbs2_tx_signal_scaling:
    type: f64
    desc: Scale of resulting signal.
    path: radio/dvbs2/tx/config/signal_scaling
    default: 1.0
    min: 0.0
    max: 10.0
    step: 0.1

  # ============================================
  # GFSK TX Configuration
  # ============================================
  gfsk_tx_force_on:
    type: boolean
    desc: Force the channel to always be on.
    path: radio/gfsk/tx/config/force_on
    default: false
    
  gfsk_tx_idle_timeout_s:
    type: u64
    desc: Power down channel after being idle for specified time.
    path: radio/gfsk/tx/config/idle_timeout_s
    default: 10
    min: 0
    max: 3600
    unit: seconds
    
  gfsk_tx_fe_frequency:
    type: f64
    desc: Frequency to receive from.
    path: radio/gfsk/tx/config/fe/frequency
    default: 401.5e6
    min: 1.0e6
    max: 1.0e9
    unit: Hz
    
  gfsk_tx_fe_gain:
    type: f64
    desc: Gain setting for gfsk TX.
    path: radio/gfsk/tx/config/fe/gain
    default: 10
    min: -10
    max: 20
    step: 0.5
    unit: dB
    
  gfsk_tx_fe_atten:
    type: f64
    desc: Digitial step attenuator setting for gfsk TX.
    path: radio/gfsk/tx/config/fe/atten
    default: 30
    min: 0
    max: 31.75
    step: 0.25
    unit: dB
    
  gfsk_tx_fe_sample_rate:
    type: f64
    desc: Sample rate of the rfic.
    path: radio/gfsk/tx/config/fe/sample_rate
    default: 400e3
    min: 100e3
    max: 10e6
    unit: Hz
    
  gfsk_tx_symbol_rate:
    type: f64
    desc: Symbol rate.  Must be integer division of sample rate.
    path: radio/gfsk/tx/config/mod/symbol_rate
    default: 12.5e3
    min: 1e3
    max: 1e6
    unit: symbols/s
    
  gfsk_tx_mod_index:
    type: f32
    desc: Modulation index.
    path: radio/gfsk/tx/config/mod_index
    default: 0.5
    min: 0.1
    max: 2.0
    step: 0.01
    
  gfsk_tx_max_payload_len:
    type: u32
    desc: Maximum payload length in bytes.
    path: radio/gfsk/tx/config/max_payload_len
    default: 128
    min: 1
    max: 65535
    unit: bytes
    
  gfsk_tx_bt:
    type: f32
    desc: 3db bandwidth symbol time product.
    path: radio/gfsk/tx/config/bt
    default: 1.0
    min: 0.1
    max: 2.0
    step: 0.1

  # ============================================
  # Anylink Configuration
  # ============================================
  anylink_active_tx_channel:
    type: string
    desc: "The channel anylink should be actively downlinking on. Valid values are: tx_uhf, tx_sband, tx_xband. You can also use an empty string to disable the active channel."
    path: space_router/config/endpoints/ep_tap0/active_tx_channel
    default: tx_sband
    options:
      - tx_uhf
      - tx_sband
      - tx_xband
      - ""
